"use client";

import { useEffect, useMemo, useState } from "react";

type Opportunity={id:string;name:string;model:string;capital:string;status:string;why:string;next:string};
type Score={demand:number;access:number;margin:number;repeatability:number;risk:number;confidence:number};
type Verification={demand:"UNVERIFIED"|"CHECKED"|"STRONG";access:"UNVERIFIED"|"CHECKED"|"STRONG";margin:"UNVERIFIED"|"CHECKED"|"STRONG";repeatability:"UNVERIFIED"|"CHECKED"|"STRONG";risk:"UNVERIFIED"|"CHECKED"|"STRONG"};
type Task={id:string;title:string;status:"READY"|"IN PROGRESS"|"BLOCKED"|"COMPLETE";opportunityId:string};
type Approval={id:string;title:string;tier:"T1"|"T2"|"T3";status:"PENDING"|"APPROVED"|"REJECTED"};
type Evidence={id:string;opportunityId:string;type:string;claim:string;source:string;checked:string;quality:"UNVERIFIED"|"CHECKED"|"STRONG";notes:string};

const opportunities:Opportunity[]=[
{id:"lead-research",name:"AI-assisted local-business lead research",model:"Service",capital:"R0 to start",status:"RESEARCH",why:"Find public business prospects, identify obvious gaps, prepare personalized outreach drafts, and let the owner approve/send them.",next:"Build a verified lead record before outreach."},
{id:"micro-service",name:"Repeatable micro-service delivery",model:"Service",capital:"R0 to start",status:"CANDIDATE",why:"Package research, data cleanup, listing optimization or simple content preparation into a deliverable that can be sold after validation.",next:"Choose one narrowly defined deliverable and create a sample workflow."},
{id:"online-tasks",name:"Legitimate online task opportunities",model:"Tasks",capital:"R0 to start",status:"PHASE 1",why:"Use verification, scoring, payout and net-earnings tracking before spending meaningful time on any task.",next:"Verify current opportunities before execution."},
{id:"pod-store",name:"Store / POD module",model:"Product",capital:"Later",status:"ROADMAP",why:"The original Store/POD plan remains intact and can be activated when research, economics and owner approval justify it.",next:"Keep separate; no publishing or spending without approval."}];

const initialTasks:Task[]=[
{id:"t1",title:"Verify the first zero-capital business workflow",status:"READY",opportunityId:"lead-research"},
{id:"t2",title:"Define evidence for opportunity verification",status:"READY",opportunityId:"lead-research"},
{id:"t3",title:"Select the first micro-service to prototype",status:"READY",opportunityId:"micro-service"}];

const scores:Record<string,Score>={
"lead-research":{demand:4,access:5,margin:4,repeatability:5,risk:4,confidence:2},
"micro-service":{demand:3,access:5,margin:4,repeatability:4,risk:4,confidence:2},
"online-tasks":{demand:4,access:4,margin:2,repeatability:3,risk:3,confidence:2},
"pod-store":{demand:3,access:3,margin:3,repeatability:4,risk:2,confidence:1}};
function scoreTotal(s:Score){return s.demand+s.access+s.margin+s.repeatability+s.risk+s.confidence}
const verificationLabels:Record<keyof Omit<Verification,"risk">,string>={demand:"Demand evidence",access:"Customer/prospect access",margin:"Economics evidence",repeatability:"Repeatable delivery"};
const verificationKeys:(keyof Verification)[]=["demand","access","margin","repeatability","risk"];
function levelValue(v:Verification[keyof Verification]){return v==="STRONG"?1:v==="CHECKED"?0.5:0}
function verificationPercent(v:Verification){return Math.round(verificationKeys.reduce((n,k)=>n+levelValue(v[k]),0)/verificationKeys.length*100)}

const initialEvidence:Evidence[]=[
{id:"e1",opportunityId:"lead-research",type:"DESIGN",claim:"Public business information can be researched without paid access.",source:"Workflow design — needs live verification",checked:"2026-09-23",quality:"UNVERIFIED",notes:"Do not treat this as proof of demand or revenue."}];

export default function Home(){
 const [tasks,setTasks]=useState<Task[]>(initialTasks),[approvals,setApprovals]=useState<Approval[]>([]),[evidence,setEvidence]=useState<Evidence[]>(initialEvidence),[selected,setSelected]=useState<Opportunity|null>(null),[tab,setTab]=useState<"overview"|"evidence"|"scoring">("overview"),[saved,setSaved]=useState(false),[verification,setVerification]=useState<Record<string,Verification>>({}),[dbStatus,setDbStatus]=useState<"checking"|"connected"|"local">("checking");
 useEffect(()=>{(async()=>{try{const r=await fetch("/api/ledger",{cache:"no-store"});const s=await r.json();if(s.configured){if(Array.isArray(s.tasks)&&s.tasks.length)setTasks(s.tasks.map((x: any)=>({id:x.id,title:x.title,status:x.status,opportunityId:x.opportunity_id})));if(Array.isArray(s.approvals))setApprovals(s.approvals);if(Array.isArray(s.evidence)&&s.evidence.length)setEvidence(s.evidence.map((x:any)=>({id:x.id,opportunityId:x.opportunity_id,type:x.type,claim:x.claim,source:x.source,checked:x.checked_on,quality:x.quality,notes:x.notes||""})));if(Array.isArray(s.verification)){const m:Record<string,Verification>={};s.verification.forEach((x:any)=>{m[x.opportunity_id]={demand:x.demand,access:x.access,margin:x.margin,repeatability:x.repeatability,risk:x.risk}});setVerification(m)}setDbStatus("connected")}else setDbStatus("local")}catch{setDbStatus("local")}})()},[]);
 useEffect(()=>{try{localStorage.setItem("aba-mvp-v2",JSON.stringify({tasks,approvals,evidence,verification}));setSaved(true);const t=setTimeout(()=>setSaved(false),900);return()=>clearTimeout(t)}catch{}},[tasks,approvals,evidence,verification]);
 const complete=tasks.filter(t=>t.status==="COMPLETE").length,pending=approvals.filter(a=>a.status==="PENDING").length,checked=evidence.filter(e=>e.quality!=="UNVERIFIED").length;
 const nextTask=useMemo(()=>tasks.find(t=>t.status!=="COMPLETE"),[tasks]);
 async function sync(action:string,payload:any){try{await fetch("/api/ledger",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,payload})})}catch{} }\n function advanceTask(id:string){setTasks(x=>{const next=x.map(t=>t.id===id?{...t,status:t.status==="READY"?"IN PROGRESS":t.status==="IN PROGRESS"?"COMPLETE":t.status}:t);const t=next.find(t=>t.id===id);if(t)sync("task",{id:t.id,status:t.status});return next})}
 function requestApproval(){const a={id:crypto.randomUUID(),title:"Owner approval: proceed with the first verified business experiment",tier:"T2" as const,status:"PENDING" as const};setApprovals(x=>[a,...x]);sync("approval-create",a)}
 function decideApproval(id:string,status:"APPROVED"|"REJECTED"){setApprovals(x=>x.map(a=>a.id===id?{...a,status}:a));sync("approval-decide",{id,status})}
 function addEvidence(opportunityId:string){const e={id:crypto.randomUUID(),opportunityId,type:"NOTE",claim:"New evidence record awaiting verification",source:"Enter source URL or identifier",checked:new Date().toISOString().slice(0,10),quality:"UNVERIFIED" as const,notes:"Verify before using this record for a business decision."};setEvidence(x=>[e,...x]);sync("evidence-create",{id:e.id,opportunity_id:e.opportunityId,type:e.type,claim:e.claim,source:e.source,checked_on:e.checked,quality:e.quality,notes:e.notes})}
 function verifyEvidence(id:string){setEvidence(x=>{const next=x.map(e=>e.id===id?{...e,quality:e.quality==="UNVERIFIED"?"CHECKED":"STRONG"}:e);const e=next.find(e=>e.id===id);if(e)sync("evidence-quality",{id:e.id,quality:e.quality});return next})}
 function getVerification(id:string):Verification{return verification[id]||{demand:"UNVERIFIED",access:"UNVERIFIED",margin:"UNVERIFIED",repeatability:"UNVERIFIED",risk:"UNVERIFIED"}}
 function advanceVerification(id:string,key:keyof Verification){setVerification(v=>{const cur=getVerification(id)[key];const next=cur==="UNVERIFIED"?"CHECKED":cur==="CHECKED"?"STRONG":"STRONG";const updated={...v,[id]:{...getVerification(id),[key]:next}};sync("verification",{opportunity_id:id,...updated[id]});return updated})}
 return <main className="shell">
  <header className="top"><div><div className="brand">Autonomous Business Agent</div><div className="subbrand">Opportunity + Evidence + Task Ledger</div></div><span className="badge">MVP • {dbStatus==="connected"?"DB CONNECTED":dbStatus==="checking"?"DB CHECKING":saved?"LOCAL SAVED":"LOCAL FALLBACK"}</span></header>
  <section className="hero"><div className="eyebrow">OWNER-CONTROLLED BUSINESS ENGINE</div><h1>From ideas to evidence-backed action.</h1><p>The dashboard now has a real MVP ledger: opportunities, tasks, evidence and approvals are recorded together. Revenue stays at zero until actual results are verified.</p><div className="notice"><strong>Control boundary:</strong> account creation, KYC, payments, wallets, accepting terms and irreversible actions remain owner-controlled.</div></section>
  <section className="grid metrics"><div className="card"><div className="muted">Actual revenue</div><div className="metric">R0.00</div><div className="muted">Verified revenue only.</div></div><div className="card"><div className="muted">Tasks complete</div><div className="metric">{complete}/{tasks.length}</div><div className="muted">Persistent MVP ledger.</div></div><div className="card"><div className="muted">Evidence checked</div><div className="metric">{checked}/{evidence.length}</div><div className="muted">Unverified claims stay flagged.</div></div></section>
  <div className="tabs"><button className={tab==="overview"?"tab active":"tab"} onClick={()=>setTab("overview")}>Operations</button><button className={tab==="evidence"?"tab active":"tab"} onClick={()=>setTab("evidence")}>Evidence ledger</button><button className={tab==="scoring"?"tab active":"tab"} onClick={()=>setTab("scoring")}>Scoring</button></div>
  {tab==="scoring"?<section className="section card"><div className="section-head"><div><div className="eyebrow">06 · OPPORTUNITY SCORING</div><h2>Verification scorecard</h2><p className="muted">This is a prioritization aid, not a probability of success. Raw fit scores stay separate from evidence verification.</p></div></div>{opportunities.map(o=>{const s=scores[o.id],v=getVerification(o.id),pct=verificationPercent(v);return <div className="evidence" key={o.id}><div style={{width:"100%"}}><div className="section-head"><div><strong>{o.name}</strong><div className="muted">Raw fit {scoreTotal(s)}/30 · Evidence verification {pct}%</div></div><span className="pill">{pct}% verified</span></div><div className="verification-grid">{verificationKeys.map(k=><button key={k} className="small-button" onClick={()=>advanceVerification(o.id,k)}>{k==="risk"?"Risk/compliance understanding":verificationLabels[k as keyof Omit<Verification,"risk">]} · {v[k]}</button>)}</div></div></div>)}</section>:{tab==="overview"?<><section className="section"><div className="section-head"><div><div className="eyebrow">01 · OPPORTUNITY ENGINE</div><h2>Business opportunity board</h2></div><button className="button" onClick={requestApproval}>Request approval</button></div><div className="cards">{opportunities.map(o=><button className="opportunity card" key={o.id} onClick={()=>setSelected(o)}><div className="op-top"><span className="pill">{o.status}</span><span className="muted">{o.capital}</span></div><h3>{o.name}</h3><p className="muted">{o.why}</p><div className="next">Next: {o.next}</div></button>)}</div></section>
  <section className="section grid two"><div className="card"><div className="eyebrow">02 · TASK LEDGER</div><h2>Execution queue</h2>{tasks.map(t=><div className="row" key={t.id}><div><strong>{t.title}</strong><div className="muted">{t.status}</div></div><button className="small-button" disabled={t.status==="COMPLETE"} onClick={()=>advanceTask(t.id)}>{t.status==="READY"?"Start":t.status==="IN PROGRESS"?"Complete":"Done"}</button></div>)}</div><div className="card"><div className="eyebrow">03 · APPROVAL CENTER</div><h2>Owner decisions</h2>{approvals.length===0&&<p className="muted">No approval requests yet.</p>}{approvals.map(a=><div className="row" key={a.id}><div><strong>{a.title}</strong><div className="muted">{a.tier} · {a.status}</div></div>{a.status==="PENDING"&&<div className="actions"><button className="small-button" onClick={()=>decideApproval(a.id,"APPROVED")}>Approve</button><button className="small-button" onClick={()=>decideApproval(a.id,"REJECTED")}>Reject</button></div>}</div>)}</div></section></>:<section className="section card"><div className="section-head"><div><div className="eyebrow">04 · EVIDENCE LEDGER</div><h2>Claims, sources and verification</h2><p className="muted">Every material opportunity claim should have a source, check date, quality state and notes. Estimates are not earnings.</p></div><button className="button" onClick={()=>addEvidence(selected?.id||opportunities[0].id)}>Add evidence</button></div>{evidence.map(e=>{const o=opportunities.find(x=>x.id===e.opportunityId);return <div className="evidence" key={e.id}><div><strong>{e.claim}</strong><div className="muted">{o?.name} · {e.type}</div><div className="source">Source: {e.source}</div><div className="muted">Checked: {e.checked} · Notes: {e.notes}</div></div><div className="actions"><span className={e.quality==="UNVERIFIED"?"pill warning":"pill"}>{e.quality}</span><button className="small-button" onClick={()=>verifyEvidence(e.id)}>{e.quality==="UNVERIFIED"?"Verify":"Strengthen"}</button></div></div>})}</section>}
  <section className="section card architecture"><div className="eyebrow">05 · CONTROLLED LOOP</div><h2>Discover → Verify → Score → Approve → Execute → Record → Reconcile → Audit → Improve</h2><p className="muted">Next engineering layer: move this ledger from browser storage to a real database. I will stop and tell you exactly what connector to add when we reach that point.</p>{nextTask&&<div className="next"><strong>Next queued task:</strong> {nextTask.title}</div>}</section>
  {selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><div className="modal card" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><div className="eyebrow">OPPORTUNITY DETAIL</div><h2>{selected.name}</h2><p className="muted">{selected.why}</p><div className="detail"><span>Model</span><strong>{selected.model}</strong><span>Starting capital</span><strong>{selected.capital}</strong><span>Status</span><strong>{selected.status}</strong></div><div className="next">Next action: {selected.next}</div><button className="button modal-button" onClick={()=>{setTab("evidence");setSelected(null)}}>Open evidence ledger</button></div></div>}
 </main>
}