"use client";

import { useEffect, useMemo, useState } from "react";

type Opportunity={id:string;name:string;model:string;capital:string;status:string;why:string;next:string};
type Task={id:string;title:string;status:"READY"|"IN PROGRESS"|"BLOCKED"|"COMPLETE";opportunityId:string};
type Approval={id:string;title:string;tier:"T1"|"T2"|"T3";status:"PENDING"|"APPROVED"|"REJECTED"};
type Evidence={id:string;opportunityId:string;type:string;claim:string;source:string;checked:string;quality:"UNVERIFIED"|"CHECKED"|"STRONG";notes:string};

const opportunities:Opportunity[]=[
{id:"lead-research",name:"AI-assisted local-business lead research",model:"Service",capital:"R0 to start",status:"RESEARCH",why:"Find public business prospects, identify obvious gaps, prepare personalized outreach drafts, and let the owner approve/send them.",next:"Build a verified lead record before outreach."},
{id:"micro-service",name:"Repeatable micro-service delivery",model:"Service",capital:"R0 to start",status:"CANDIDATE",why:"Package research, data cleanup, listing optimization or simple content preparation into a deliverable that can be sold after validation.",next:"Choose one narrowly defined deliverable and create a sample workflow."},
{id:"online-tasks",name:"Legitimate online task opportunities",model:"Tasks",capital:"R0 to start",status:"PHASE 1",why:"Use verification, scoring, payout and net-earnings tracking before spending meaningful time on any task.",next:"Verify current opportunities before execution."},
{id:"pod-store",name:"Store / POD module",model:"Product",capital:"Later",status:"ROADMAP",why:"The original Store/POD plan remains intact and can be activated when research, economics and owner approval justify it.",next:"Keep separate; no publishing or spending without approval."}];

const initialTasks:Task[]=[
{id:"t1",title:"Verify the first zero-capital business workflow",status:"READY",opportunityId:"lead-research"},
{id:"t2",title:"Define evidence for opportunity verification",status:"READY",opportunityId:"lead-research"},
{id:"t3",title:"Select the first micro-service to prototype",status:"READY",opportunityId:"micro-service"}];

const initialEvidence:Evidence[]=[
{id:"e1",opportunityId:"lead-research",type:"DESIGN",claim:"Public business information can be researched without paid access.",source:"Workflow design — needs live verification",checked:"2026-09-23",quality:"UNVERIFIED",notes:"Do not treat this as proof of demand or revenue."}];

export default function Home(){
 const [tasks,setTasks]=useState<Task[]>(initialTasks),[approvals,setApprovals]=useState<Approval[]>([]),[evidence,setEvidence]=useState<Evidence[]>(initialEvidence),[selected,setSelected]=useState<Opportunity|null>(null),[tab,setTab]=useState<"overview"|"evidence">("overview"),[saved,setSaved]=useState(false);
 useEffect(()=>{try{const r=localStorage.getItem("aba-mvp-v2");if(r){const s=JSON.parse(r);if(Array.isArray(s.tasks))setTasks(s.tasks);if(Array.isArray(s.approvals))setApprovals(s.approvals);if(Array.isArray(s.evidence))setEvidence(s.evidence)}}catch{}},[]);
 useEffect(()=>{try{localStorage.setItem("aba-mvp-v2",JSON.stringify({tasks,approvals,evidence}));setSaved(true);const t=setTimeout(()=>setSaved(false),900);return()=>clearTimeout(t)}catch{}},[tasks,approvals,evidence]);
 const complete=tasks.filter(t=>t.status==="COMPLETE").length,pending=approvals.filter(a=>a.status==="PENDING").length,checked=evidence.filter(e=>e.quality!=="UNVERIFIED").length;
 const nextTask=useMemo(()=>tasks.find(t=>t.status!=="COMPLETE"),[tasks]);
 function advanceTask(id:string){setTasks(x=>x.map(t=>t.id===id?{...t,status:t.status==="READY"?"IN PROGRESS":t.status==="IN PROGRESS"?"COMPLETE":t.status}:t))}
 function requestApproval(){setApprovals(x=>[...x,{id:String(Date.now()),title:"Owner approval: proceed with the first verified business experiment",tier:"T2",status:"PENDING"}])}
 function decideApproval(id:string,status:"APPROVED"|"REJECTED"){setApprovals(x=>x.map(a=>a.id===id?{...a,status}:a))}
 function addEvidence(){if(!selected)return;setEvidence(x=>[...x,{id:String(Date.now()),opportunityId:selected.id,type:"NOTE",claim:"New evidence record awaiting verification",source:"Enter source URL or identifier",checked:new Date().toISOString().slice(0,10),quality:"UNVERIFIED",notes:"Verify before using this record for a business decision."}])}
 return <main className="shell">
  <header className="top"><div><div className="brand">Autonomous Business Agent</div><div className="subbrand">Opportunity + Evidence + Task Ledger</div></div><span className="badge">MVP • {saved?"SAVED":"READY"}</span></header>
  <section className="hero"><div className="eyebrow">OWNER-CONTROLLED BUSINESS ENGINE</div><h1>From ideas to evidence-backed action.</h1><p>The dashboard now has a real MVP ledger: opportunities, tasks, evidence and approvals are recorded together. Revenue stays at zero until actual results are verified.</p><div className="notice"><strong>Control boundary:</strong> account creation, KYC, payments, wallets, accepting terms and irreversible actions remain owner-controlled.</div></section>
  <section className="grid metrics"><div className="card"><div className="muted">Actual revenue</div><div className="metric">R0.00</div><div className="muted">Verified revenue only.</div></div><div className="card"><div className="muted">Tasks complete</div><div className="metric">{complete}/{tasks.length}</div><div className="muted">Persistent MVP ledger.</div></div><div className="card"><div className="muted">Evidence checked</div><div className="metric">{checked}/{evidence.length}</div><div className="muted">Unverified claims stay flagged.</div></div></section>
  <div className="tabs"><button className={tab==="overview"?"tab active":"tab"} onClick={()=>setTab("overview")}>Operations</button><button className={tab==="evidence"?"tab active":"tab"} onClick={()=>setTab("evidence")}>Evidence ledger</button></div>
  {tab==="overview"?<><section className="section"><div className="section-head"><div><div className="eyebrow">01 · OPPORTUNITY ENGINE</div><h2>Business opportunity board</h2></div><button className="button" onClick={requestApproval}>Request approval</button></div><div className="cards">{opportunities.map(o=><button className="opportunity card" key={o.id} onClick={()=>setSelected(o)}><div className="op-top"><span className="pill">{o.status}</span><span className="muted">{o.capital}</span></div><h3>{o.name}</h3><p className="muted">{o.why}</p><div className="next">Next: {o.next}</div></button>)}</div></section>
  <section className="section grid two"><div className="card"><div className="eyebrow">02 · TASK LEDGER</div><h2>Execution queue</h2>{tasks.map(t=><div className="row" key={t.id}><div><strong>{t.title}</strong><div className="muted">{t.status}</div></div><button className="small-button" disabled={t.status==="COMPLETE"} onClick={()=>advanceTask(t.id)}>{t.status==="READY"?"Start":t.status==="IN PROGRESS"?"Complete":"Done"}</button></div>)}</div><div className="card"><div className="eyebrow">03 · APPROVAL CENTER</div><h2>Owner decisions</h2>{approvals.length===0&&<p className="muted">No approval requests yet.</p>}{approvals.map(a=><div className="row" key={a.id}><div><strong>{a.title}</strong><div className="muted">{a.tier} · {a.status}</div></div>{a.status==="PENDING"&&<div className="actions"><button className="small-button" onClick={()=>decideApproval(a.id,"APPROVED")}>Approve</button><button className="small-button" onClick={()=>decideApproval(a.id,"REJECTED")}>Reject</button></div>}</div>)}</div></section></>:<section className="section card"><div className="section-head"><div><div className="eyebrow">04 · EVIDENCE LEDGER</div><h2>Claims, sources and verification</h2><p className="muted">Every material opportunity claim should have a source, check date, quality state and notes. Estimates are not earnings.</p></div><button className="button" onClick={()=>{if(!selected)setSelected(opportunities[0]);addEvidence()}}>Add evidence</button></div>{evidence.map(e=>{const o=opportunities.find(x=>x.id===e.opportunityId);return <div className="evidence" key={e.id}><div><strong>{e.claim}</strong><div className="muted">{o?.name} · {e.type}</div><div className="source">Source: {e.source}</div><div className="muted">Checked: {e.checked} · Notes: {e.notes}</div></div><span className={e.quality==="UNVERIFIED"?"pill warning":"pill"}>{e.quality}</span></div>})}</section>}
  <section className="section card architecture"><div className="eyebrow">05 · CONTROLLED LOOP</div><h2>Discover → Verify → Score → Approve → Execute → Record → Reconcile → Audit → Improve</h2><p className="muted">Next engineering layer: move this ledger from browser storage to a real database. I will stop and tell you exactly what connector to add when we reach that point.</p>{nextTask&&<div className="next"><strong>Next queued task:</strong> {nextTask.title}</div>}</section>
  {selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><div className="modal card" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><div className="eyebrow">OPPORTUNITY DETAIL</div><h2>{selected.name}</h2><p className="muted">{selected.why}</p><div className="detail"><span>Model</span><strong>{selected.model}</strong><span>Starting capital</span><strong>{selected.capital}</strong><span>Status</span><strong>{selected.status}</strong></div><div className="next">Next action: {selected.next}</div><button className="button modal-button" onClick={()=>{setTab("evidence");setSelected(null)}}>Open evidence ledger</button></div></div>}
 </main>
}